name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
    
env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    name: Build Docker Container Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag turbosnute/ps-netatmo-influxdb:$(date +%s)
